// Skeleton of this file generated by AI: https://chatgpt.com/share/6921fec2-7724-800c-920b-0850dc0d393a
import local_general from "../instructions/general_rules.md?raw";
import local_reps from "../instructions/reps_intensity.md?raw";
import local_compound from "../instructions/compound_lifts.md?raw";
import local_plyo from "../instructions/plyometrics_loading_jumps.md?raw";
import local_ballistic from "../instructions/ballistic_training.md?raw";
// import local_specific from "../instructions/specific_rules.md?raw"; // Uncomment if file exists

/**
 * Builds the complete system prompt for generating training programs.
 * * @param {object} userInput - Clean structured input from frontend.
 * @param {object} oldPlan - Previous training plan for progression (if any).
 * @param {object} liveInstructions - Object containing instructions fetched from Firebase (optional).
 * @returns {string} - The complete prompt string.
 */
export function buildTrainingPrompt(userInput, oldPlan = null, liveInstructions = null) {
    
    // Priority: Use live instructions from Firebase if available, otherwise fallback to local files.
    const instructions = {
        "general_rules": liveInstructions?.["general_rules"] || local_general,
        "reps_intensity": liveInstructions?.["reps_intensity"] || local_reps,
        "compound_lifts": liveInstructions?.["compound_lifts"] || local_compound,
        "plyometrics_loading_jumps": liveInstructions?.["plyometrics_loading_jumps"] || local_plyo,
        "ballistic_training": liveInstructions?.["ballistic_training"] || local_ballistic
    };

    const guidelines = Object.values(instructions)
        .filter(text => text && typeof text === 'string') 
        .join("\n\n");

    // Combine everything into the final prompt
    const prompt = `
You are **PowerTrainingCoach**, an expert AI specializing in creating safe, effective, and personalized strength & conditioning training programs for combat athletes.

Follow ALL of the domain rules and instructions below:

${guidelines}

Always adapt the plan to:
- primary combat sport and style focus (striking/grappling/balanced)
- weight class (manage volume/intensity for the class)
- upcoming competition period (off-season, pre-season, fight camp, in-season)
- equipment access (full gym vs minimal/home)
- injuries and weaknesses (avoid aggravating, include prehab where sensible)
- focus emphasis (more sparring/technique vs more conditioning)
- requested weekly frequency

---

### USER INPUT (JSON):
${JSON.stringify(userInput, null, 2)}

---

### OUTPUT INSTRUCTIONS:
- Respond ONLY in valid JSON.
- Follow the structure below EXACTLY.
- Do not include commentary or explanation.

{
  "weeks": [
    {
      "week": 1,
      "days": [
        {
          "day": 1,
          "exercises": [
            {
              "name": "Exercise Name",
              "sets": "3–5",
              "reps": "8–12",
              "notes": "Short instruction or coaching cue"
            }
          ]
        }
      ]
    }
  ]
}

### Previous Plan (if any):
${oldPlan ? JSON.stringify(oldPlan, null, 2) : "No previous plan provided."}

---

###

Now generate the training plan JSON.
`;

    return prompt;
}