// Basic file generated by AI: https://chatgpt.com/share/6921fec2-7724-800c-920b-0850dc0d393a
import { OPENAI_API_URL, OPENAI_API_MODEL, OPENAI_API_TEMPERATURE } from "./config/apiConfig.js";
import { buildTrainingPrompt } from "./utils/promptBuilder.js";
import { getApiConfig, getLiveInstructions } from "./models/dbService.js";

export async function generatePlan(userInput, oldPlan = null) {
    let apiKey = null;
    let liveInstructions = null;

    try {
        // Fetch secure config and live instructions from Firebase
        const [dbConfig, dbInstructions] = await Promise.all([
            getApiConfig(),
            getLiveInstructions()
        ]);

        // STRICT: We only accept the key from the Database
        if (dbConfig && dbConfig.openai_key) {
            apiKey = dbConfig.openai_key;
        } else {
            // If DB works but key is missing
            throw new Error("Configuration Error: No OpenAI API Key found in Firestore.");
        }

        if (dbInstructions) {
            liveInstructions = dbInstructions;
        }

    } catch (error) {
        // If DB connection fails, we stop here because we have no API Key.
        console.error("Critical: Failed to fetch API Config from DB.", error);
        throw new Error("Service temporarily unavailable. Could not retrieve security credentials.");
    }

    // Security Check
    if (!apiKey) {
        throw new Error("Authentication failed: Missing API Key.");
    }

    const prompt = buildTrainingPrompt(userInput, oldPlan, liveInstructions);

    const payload = {
        model: OPENAI_API_MODEL,
        temperature: OPENAI_API_TEMPERATURE,
        messages: [
            {
                role: "system",
                content: prompt
            }
        ],
        response_format: { type: "json_object" }
    };

    const options = {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify(payload)
    };

    return fetch(OPENAI_API_URL, options)
        .then(response => response.json())
        .then(result => {
            if (result.error) {
                throw new Error(`OpenAI API Error: ${result.error.message}`);
            }
            const content = result?.choices?.[0]?.message?.content;
            if (!content) {
                throw new Error(`No content in API response: ${JSON.stringify(result)}`);
            }
            return JSON.parse(content);
        });
}